name: seth_flutter
description: A try at flutter with my Seth app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.14.0+3
  http: ^0.12.2
  sqflite: ^1.3.1
  path: ^1.6.4
  rxdart: ^0.24.1
  dartz: ^0.9.1
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  grouped_list: ^3.3.0
  webview_flutter: ^0.3.22+1

  google_sign_in: ^4.5.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7

  get_it: ^4.0.4
  moor_flutter: ^3.1.0
  injectable: ^1.0.4
  flushbar: ^1.10.4
  uuid: ^2.2.0
  auto_route: ^0.6.7
  kt_dart: ^0.7.0+1
  json_annotation: ^3.0.1
  freezed_annotation: ^0.11.0+1
  flutter_hooks: ^0.13.0
  flutter_statusbarcolor: ^0.2.3
  recursive_regex: ^0.1.3+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  freezed: ^0.11.4
  lint: ^1.2.0
  build_runner:
  moor_generator: ^3.3.0
  injectable_generator: ^1.0.3
  auto_route_generator: ^0.6.7
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/infrastructure/core/assets/seth_logo.png
    - lib/infrastructure/core/assets/seth_data.db
    - lib/infrastructure/core/assets/geometric-01.png
    - lib/infrastructure/core/assets/geometric-02.png
    - lib/infrastructure/core/assets/geometric-03.png
    - lib/infrastructure/core/assets/geometric-04.png
    - lib/infrastructure/core/assets/geometric-05.png
    - lib/infrastructure/core/assets/geometric-06.png

  uses-material-design: true

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
